# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Drones
email: akamath426@gmail.com
description: This website is dedicated to all things drones. Made for TSA competition as webmaster
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://andykamath.com" # the base hostname & protocol for your site
twitter_username: baesedandy
github_username:  andykamath

# Build settings
markdown: kramdown
